{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/berita": {
      "get": {
        "summary": "Berita",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/berita/detail/{slug}": {
      "get": {
        "summary": "Berita Detail",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "berita-1-aja",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/berita-list": {
      "get": {
        "summary": "Berita List",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "filter[search]",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/blog-list": {
      "get": {
        "summary": "Blog List",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "filter[search]",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/blog/detail/{slug}": {
      "get": {
        "summary": "Blog Detail",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "peternakan-pembibitan",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/blog": {
      "get": {
        "summary": "Blog",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/karir": {
      "get": {
        "summary": "Karir",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/karir-list": {
      "get": {
        "summary": "Karir List",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "filter[search]",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "",
            "required": false,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/karir/{slug}": {
      "get": {
        "summary": "Karir Detail",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "lowongan-marketing",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/keberlanjutan/{slug}": {
      "get": {
        "summary": "Keberlanjutan",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "pendekatan-dan-kinerja-manajemen",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/keberlanjutan-laporan-list": {
      "get": {
        "summary": "Laporan Keberlanjutan",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "filter[search]",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pengumuman-list": {
      "get": {
        "summary": "Pengumuman List",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "filter[search]",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pengumuman/detail/{slug}": {
      "get": {
        "summary": "Pengumuman Detail",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "test-pengumuman",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pengumuman": {
      "get": {
        "summary": "Pengumuman",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/relasi-investor/{slug}": {
      "get": {
        "summary": "Relasi Investor",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "prospektus",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/relasi-investor/{slug}/list": {
      "get": {
        "summary": "Relasi Investor List",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "prospektus",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "filter[search]",
            "in": "query",
            "description": "",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "",
            "required": false,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/": {
      "get": {
        "summary": "Beranda",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/hubungi-kami": {
      "get": {
        "summary": "Hubungi Kami",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/lini-bisnis/{slug}": {
      "get": {
        "summary": "Lini Bisnis",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "slug",
            "in": "path",
            "description": "",
            "required": true,
            "example": "pembibitan",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/produk": {
      "get": {
        "summary": "Produk",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/tentang-perusahaan": {
      "get": {
        "summary": "Tentang Perusahaan",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": false,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "success": true,
                  "message": "Berhasil mengambil data.",
                  "data": null,
                  "errors": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}